### ISSUE TITLE
Error when shipping to HELK

### ISSUE THREAD

**Issue by jcastillo725** [OTRF/Security-Datasets#42]
I'm encountering an error when trying to ship datasets to HELK.

![image](https://user-images.githubusercontent.com/81306595/114980372-f23d2380-9ebe-11eb-9ffe-e16b5472618e.png)

**Comment by sec-balkan** [comment]
Have you been able to solve it?

**Comment by blueteambram** [comment]
Try running sudo pip3 install elasticsearch

**Comment by Cyb3rWard0g** [comment]
Hello @jcastillo725 ! It has been a while since I tried to send data to HELK. However, I know @thomaspatzke does it for his project 

https://github.com/thomaspatzke/elk-detection-lab

He contributed the script to the project, but I have not tested it myself. @thomaspatzke , would it be possible whenever you have some time to test it with your project if you do not mind? I know you are very busy so whenever you have time :) Thank you man!

**Comment by thomaspatzke** [comment]
Sure, Roberto! Can you assign it to me so that it doesn't gets lost? For me it appears that the elasticsearch library is not present.

**Comment by Cyb3rWard0g** [comment]
Hello @thomaspatzke ! I did not pay attention to the error and got confused with another issue that also talked about sending data to an ELK stack. I thought they were similar ones. Yes the error is pretty straightforward 😂 sorry to bother you with this. I hope you have a great weekend!

**Comment by thomaspatzke** [comment]
Good occasion to update the link to Mordor to the current version 😉

**Comment by Cyb3rWard0g** [comment]
Ohhh yes! Yay! 😅
